# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: tsServices${opt:user, self:custom.defaultUser}

custom:
  defaultUser: ''
  baseUrl: ''
  defaultStage: 'local'
  defaultRegion: 'ap-southeast-1'
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.defaultRegion}
  profile: ${opt:profile, self:provider.stage}
  timeout: 60
  # Set environment variables
  environment: ${file(./config/env.yml):${self:provider.stage}}
  # Set IAM role
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:*"
      Resource:
        - '*'

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  authorizer:
    handler: src/services/auth/authorizer.default
  login:
    handler: src/services/auth/login.default
    events:
      - http:
          method: POST
          path: auth/login
          cors: true
          # authorizer:
          #   name: authorizer
          #   resultTtlInSeconds: 0
  candidateApply:
    handler: src/services/candidate/apply.default
    events:
      - http:
          method: POST
          path: candidate/apply
          cors: true
  employerApply:
    handler: src/services/employer/apply.default
    events:
      - http:
          method: POST
          path: employer/apply
          cors: true
